### ISSUE TITLE
YAML testcase input

### ISSUE THREAD

**Issue by nicolasreich** [magnusbaeck/logstash-filter-verifier#102]
Is it possible to specify the input of a test case directly in YAML instead of as a string?

Basically, write this:

```yaml
---
testcases:
  - input:
      - field1: value1
        field2: value2
    expected:
      - field1: modified_value1
        field2: modified_value2
```

Instead of:

```yaml
---
codec: json_lines
testcases:
  - input:
      - >
      {
      - "field1": "value1",
        "field2": "value2"
      }
    expected:
      - field1: modified_value1
        field2: modified_value2
```
