### ISSUE TITLE
Unable to inject ints into events using fields

### ISSUE THREAD

**Issue by jgough** [magnusbaeck/logstash-filter-verifier#133]
I raised this briefly in passing in https://github.com/magnusbaeck/logstash-filter-verifier/issues/132 but wanted to raise it separately here so that it did not get lost.

The test:
```
fields:
  bar: 1234
input_plugin: "pipeline2_input"
testcases:
  - input:
      - foo
    expected:
      - message: foo
```
fails setting bar:1234 with the error
```
logstash-filter-verifier: error: Error reading/unmarshalling /usr/share/logstash/tests/test2.yml: Problem converting field "bar" to Logstash format: Unsupported type int: 1234
```

Is this behaviour correct?  I have an input plugin that sets a field equal to a number (current line number of the file) and it seems I cannot currently inject using `fields` this way.
