### ISSUE TITLE
Test single filter in daemon mode?

### ISSUE THREAD

**Issue by nicolasreich** [magnusbaeck/logstash-filter-verifier#139]
### Description

With LFV 1.x and with LFV 2.0 in standalone mode, it's possible to test a single filter, without input or output. If I have those files:

`mutate.conf`

```logstash
filter {
  mutate { 
    rename => { "before" => "after" }
  }
}
```

`mutate.test.yaml`

```yaml
---
codec: json_lines
ignore:
  - "@timestamp"
  - host
testcases:
  - input:
      - >
        {
          "before": "hello"
        }
    expected:
      - after: "hello"
```

I can run `logstash-filter-verifier standalone mutate.test.yaml mutate.conf` and the test runs fine. I haven't found a way to do this simply with the daemon mode.

### Motivation

If a pipeline is made of several files, each containing one or more files, I'd like to be able to test them independently. Moreover, I'd like to be able to do this in daemon mode to spare some time.

A simple workaround would be to have a dummy input and output in a folder, a pipeline.yml file pointing to this folder, and copy each file to test in this folder one after the other. It would work fine, but it's a bit reimplementing something that's already in LFV.

### Possible Drawbacks

In case it's not already implemented and I just missed it, it might be difficult to implement; and I do realize that now the priority is LFV 2.0 with its current set of features, not extending it, but I wanted to share this before forgetting.
