### ISSUE TITLE
Question about fields

### ISSUE THREAD

**Issue by cwiechmann** [magnusbaeck/logstash-filter-verifier#83]
I have the following Filebeat config, which is setting the type based on the input Log-File:
```
- input_type: log
  paths: ["/var/log/work/*.log"]
  fields:
    type: openlog
- input_type: log
  paths: ["/var/log/trace/*.trc"]
  fields:
    type: trace
```

In my logstash config, when using the following if clause, it works as expected:
```
if ([fields][type] == "openlog") {
```
This behavior I would like to test with the LFV, hence I configured my test like so:
```json
{
    "fields": {
      "type": "openlog"
    },
    "codec": "json_lines",
    "testcases": [
      {
```
but this doesn't work. It only works, when changing my logstash config to this expression: `if ([type] == "openlog") {`, but then it is no longer working with Filebeat.

Do I missed anything?

**Comment by cwiechmann** [comment]
I have discovered an option in filebeat to place configured fields under root. With that set to true, the LFV behaves as Filebeat. Perhaps a note in the readme might be useful. 

```
- input_type: log
  paths: ["/var/log/work/*.log"]
  fields_under_root: true
  fields:
    type: openlog
- input_type: log
  paths: ["/var/log/trace/*.trc"]
  fields_under_root: true
  fields:
    type: trace
```
